version: '3.9'

services:
    db:
      image: postgres:12.0-alpine
      volumes:
        - postgres_data_dash:/var/lib/postgresql/data
      ports:
        - 5432:5432
      environment:
        - POSTGRES_DB=polygon
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=supersecretpassword
      networks:
        node_net:
          ipv4_address: 172.28.1.2

    web:
      build: .
      user: "${UID}:${GID}"
      working_dir: /usr/src/app
      restart: always
      container_name: 'web_app'
      command: python app.py
      volumes:
        - .:/usr/src/app
      ports:
        - '8050:8050'
      depends_on:
        - db
      networks:
        node_net:
          ipv4_address: 172.28.1.3
    
    worker:
      build: .
      user: "${UID}:${GID}"
      working_dir: /usr/src/app
      restart: always
      container_name: 'worker'
      command: python worker.py
      volumes:
        - .:/usr/src/app
      depends_on:
        - db
      networks:
        node_net:
          ipv4_address: 172.28.1.4

#postgres volume
volumes:
    postgres_data_dash:


# networking for the containers
networks:
    node_net:
      ipam:
        driver: default
        config:
          - subnet: 172.28.0.0/16
